version: 2
jobs:
  build:
    docker:
    - image: jberryman/graphql-engine-server-builder-8.10:2020-04-29
    resource_class: large
    working_directory: ~/graphql-parser
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cabal-store-v2-{{ checksum "cabal.project" }}-{{ checksum "graphql-parser.cabal" }}
            - cabal-store-v2-{{ checksum "cabal.project" }}
            - cabal-store-v2-
      - run:
          name: Update dependencies
          command: cabal update
      - run:
          name: Build
          command: cabal new-build
      - run:
          name: Run tests
          command: cabal new-test --test-options release
      - save_cache:
          name: Cache Dependencies
          key: cabal-store-v2-{{ checksum "cabal.project" }}-{{ checksum "graphql-parser.cabal" }}
          paths:
            - ~/.cabal/packages
            - ~/.cabal/store
workflows:
  version: 2
  workflow_v20190224:
    jobs:
    - build
